### ISSUE TITLE
Just Showing Blank where is main directory

### ISSUE THREAD

**Issue by shahzadakram700** [Zubdata/Google-Maps-Scraper#14]
![Blank](https://github.com/Zubdata/Google-Maps-Scraper/assets/145826838/42bc9dfc-a9d3-4144-9601-874dade7306b)
![Requirments install](https://github.com/Zubdata/Google-Maps-Scraper/assets/145826838/7b4f1f1c-fccb-4e3e-bebf-4137abe238a7)

Dear Sir, I install requirements using commands but when i run a file in scraper frontend.py its show blank screen and end. There is no file in main directory.

**Comment by mzubairtahir** [comment]
Hello Shahzad, please refer to this [answer](https://github.com/Zubdata/Google-Maps-Scraper/issues/9#issuecomment-1771942664)

Don't run the frontend.py in the main directory of the repo. instead, open the code folder `Google maps scraper`. And run the file in this directory.
