### ISSUE TITLE
Scraper not stopping

### ISSUE THREAD

**Issue by FujiwaraChoki** [Zubdata/Google-Maps-Scraper#5]
Hey, I love the scraper dude.
However sadly it's not stopping when it's actually done. There are no more places to click on, but it goes on and on.

Can you help with this?

![image](https://github.com/Zubdata/Google-Maps-Scraper/assets/78088687/c9c59c1e-d0cc-465e-8fe5-7b3bd062d5c0)

**Comment by mzubairtahir** [comment]
> Hey, I love the scraper dude. However sadly it's not stopping when it's actually done. There are no more places to click on, but it goes on and on.
> 
> Can you help with this?
> 
> ![image](https://user-images.githubusercontent.com/78088687/249877116-c9c59c1e-d0cc-465e-8fe5-7b3bd062d5c0.png)

**Comment by mzubairtahir** [comment]
This is because of your language is not english, 
It will end up scrolling when it will find "You have reached the end of list"
But in your case it will never found that message at the end of scrolling , so you should change your language , or change the text in code.

**Comment by FujiwaraChoki** [comment]
> This is because of your language is not english, It will end up scrolling when it will find "You have reached the end of list" But in your case it will never found that message at the end of scrolling , so you should change your language , or change the text in code.

I see, thanks bro!
