### ISSUE TITLE
error install

### ISSUE THREAD

**Issue by PauloBoaventura** [Zubdata/Google-Maps-Scraper#9]
> I thought this error was the problem...
> rodei =

    $ python3 frontend.py
Traceback (most recent call last):
   File "/home/swky/Documentos/niteroi_city_map/Google-Maps-Scraper/scraper/frontend.py", line 264, in <module>
     app = Frontend()
           ^^^^^^^^^^
   File "/home/swky/Documentos/niteroi_city_map/Google-Maps-Scraper/scraper/frontend.py", line 21, in __init__
     icon = tk.PhotoImage(file=self.pathmaker("images/GMS.png"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^
   File "/usr/lib/python3.11/tkinter/__init__.py", line 4130, in __init__
     Image.__init__(self, 'photo', name, cnf, master, **kw)
   File "/usr/lib/python3.11/tkinter/__init__.py", line 4075, in __init__
     self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "/home/swky/Documentos/niteroi_city_map/Google-Maps-Scraper/scraper/images/GMS.png": no such file or directory

> 
> 
> I copied the /images directory into /scraper
> 
> Then...
> 
> Not worked!!!

**Comment by mzubairtahir** [comment]
Hello [PauloBoaventura](https://github.com/PauloBoaventura)!

It appears that you may have accidentally run the "frontend.py" file from the subdirectory "scraper" instead of the main directory "Google Map Scraper." To correctly execute the scraper, please make sure to run it from the main directory.

**Comment by italianjesus** [comment]
but there is no scraper in the main directory?
![image](https://github.com/Zubdata/Google-Maps-Scraper/assets/54536994/6f199178-37c4-4b47-804a-0fccb09fe3a3)

**Comment by mzubairtahir** [comment]
![Screenshot 2023-10-20 064056](https://github.com/Zubdata/Google-Maps-Scraper/assets/123851862/91da1cd4-d3a8-4e32-85e9-b4cf8c0f19a8)

your directory structure should be like this when running the frontend.py file
